language: python

sudo: required
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  # lxml dropped support for Python 3.4 in version 4.4.0
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install 'lxml<4.4.0'; fi
  # use newest version of pip to avoid e.g. selection of wrong dependency versions
  - pip install -U pip
  # install application development dependencies
  - pip install -r requirements.txt

script: make test
