language: python

sudo: required
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  # lxml dropped support for Python 3.4 in version 4.4.0
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install 'lxml<4.4.0'; fi
  # in CI, incompatible zipp version is chosen for some reason
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install 'zipp<2,>=0.5'; fi
  # install application development dependencies
  - pip install -r requirements.txt

script: make test
