language: python

sudo: required
dist: trusty

python:
#  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  # lxml dropped support for Python 3.3 in version 4.3.0
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install 'lxml<4.3.0'; fi
  # lxml dropped support for Python 3.4 in version 4.4.0
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install 'lxml<4.4.0'; fi
  - pip install -r requirements.txt

script: make test
